# Generated by Django 4.0.4 on 2022-05-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
